# pcloud:
#   user: 
#   password: 

# a trick to view any month is 
# - delete data/downloaded_images/*
# - change below to yyyy-mm-xx xx.xx.xx.jpg with yyyy and mm of interest
default_first_image: '2014-11-31 18.58.45.jpg'

batch_size: 200

pic_root_folderid: 2415499913

download_folder: data/downloaded_images
